import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import "./globals.css";
import enMessages from "../../../messages/en"; // Path to your English messages
import idMessages from "../../../messages/id"; // Path to your German messages
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  params: { locale: string };
  children: React.ReactNode;
}) {
  let messages;
  try {
    messages = params.locale === "en" ? enMessages : idMessages;
  } catch (error) {
    notFound();
  }
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <NextIntlClientProvider
          locale={params.locale}
          messages={messages}
          timeZone="Asia/Singapore"
          now={new Date()}
        >
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
